    - name: NGINX |install epel-release
      become: true
      ansible.builtin.yum:
        name: epel-release
        state: present
      tags:
        - distrib
        - nginx
    - name: NGINX | Install NGINX
      become: true
      ansible.builtin.yum:
        name: nginx
        state: present
      tags:
        - distrib
        - nginx
      notify: start-nginx
    - name: Config NGINX
      become: true
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      tags:
        - config
        - nginx
      notify: reload-nginx