---
# handlers file for lighthouse
- name: start-nginx
  become: true
  command: nginx
- name: reload-nginx
  become: true
  command: nginx -s reload
- name: nginx-reload
  become: true
  command: nginx -s reload